// Airs keys take precedence; legacy deployment keys are read only as migration aliases.
const airsEnv = (key: string, legacy: string) => process.env[key] ?? process.env[key.replace(/^AIRS_/, 'AIR_')] ?? process.env[legacy]

export default defineNuxtConfig({
  compatibilityDate: '2026-08-24',
  srcDir: '.',
  buildDir: process.env.FLOWST_BUILD_DIR || '.nuxt',
  // Separate local Flowst Airs, Flowst and browser-check optimizer artifacts.
  vite: { cacheDir: `${process.env.FLOWST_BUILD_DIR || '.nuxt'}/vite-cache` },
  ignore: ['**/.nuxt-*', '**/.tmp', '**/.tmp/**', '**/.output/**', '**/test-results/**', '**/playwright-report/**', '**/artifacts/**'],
  devtools: { enabled: process.env.NUXT_DEVTOOLS === 'true' },
  modules: ['@vite-pwa/nuxt'],
  css: ['~/assets/css/main.css', '~/assets/css/flowst-app.css', '~/assets/css/airs.css'],
  app: {
    head: {
      htmlAttrs: { lang: 'en' },
      title: 'Flowst Airs',
      meta: [
        { name: 'description', content: 'Bring your source. Understand, explain aloud, and apply its ideas with Flowst Airs.' },
        { name: 'theme-color', content: '#f7faff' },
        { property: 'og:title', content: 'Flowst Airs' },
        { property: 'og:description', content: 'Bring your source. Find your voice.' },
      ],
      link: [
        { rel: 'icon', href: '/airs-icon.svg', type: 'image/svg+xml' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Albert+Sans:wght@400;500;600;700&family=Unbounded:wght@500;600;700&display=swap' },
      ],
    },
  },
  runtimeConfig: {
    studyGithubToken: airsEnv('AIRS_GITHUB_READ_TOKEN', 'AMINA_GITHUB_READ_TOKEN') || '',
    studySourceFixtureMode: airsEnv('AIRS_SOURCE_FIXTURE_MODE', 'AMINA_SOURCE_FIXTURE_MODE') === 'true',
    studyVideoEnabled: airsEnv('AIRS_VIDEO_ENABLED', 'AMINA_VIDEO_ENABLED') === 'true',
    studyVideoApiKey: airsEnv('AIRS_VIDEO_API_KEY', 'AMINA_VIDEO_API_KEY') || '',
    studyVideoWebhookId: airsEnv('AIRS_VIDEO_WEBHOOK_ID', 'AMINA_VIDEO_WEBHOOK_ID') || '',
    studyVideoWebhookSecret: airsEnv('AIRS_VIDEO_WEBHOOK_SECRET', 'AMINA_VIDEO_WEBHOOK_SECRET') || '',
    studyVideoMonthlyBudgetUsd: Number(airsEnv('AIRS_VIDEO_MONTHLY_BUDGET_USD', 'AMINA_VIDEO_MONTHLY_BUDGET_USD') || 0),
    studyVideoUsdPerMinute: Number(airsEnv('AIRS_VIDEO_USD_PER_MINUTE', 'AMINA_VIDEO_USD_PER_MINUTE') || 0),
    flowstCourseModel: process.env.FLOWST_COURSE_MODEL || 'openai/gpt-oss-120b',
    flowstCoursePilotEnabled: process.env.FLOWST_COURSE_PILOT_ENABLED === 'true',
    flowstInquiryPilotEnabled: process.env.FLOWST_INQUIRY_PILOT_ENABLED === 'true',
    flowstNeuroMapV1Enabled: process.env.FLOWST_NEUROMAP_V1_ENABLED !== 'false',
    flowstAuthMode: process.env.FLOWST_AUTH_MODE || 'cognito',
    aminaRealtimeEnabled: airsEnv('AIRS_REALTIME_ENABLED', 'AMIRA_REALTIME_ENABLED') === 'true',
    studyTextProvider: airsEnv('AIRS_TEXT_PROVIDER', 'AMINA_TEXT_PROVIDER') || 'groq',
    studyVoiceProvider: airsEnv('AIRS_VOICE_PROVIDER', 'AMINA_VOICE_PROVIDER') || 'elevenlabs',
    elevenLabsStudyAgentId: process.env.ELEVENLABS_STUDY_AGENT_ID || '',
    elevenLabsStudyLlmSecret: process.env.ELEVENLABS_STUDY_LLM_SECRET || '',
    elevenLabsStudyLlmUrl: process.env.ELEVENLABS_STUDY_LLM_URL || '',
    aminaRealtimeModel: airsEnv('AIRS_REALTIME_MODEL', 'AMIRA_REALTIME_MODEL') || 'amazon.nova-2-sonic-v1:0',
    aminaRealtimeVoice: airsEnv('AIRS_REALTIME_VOICE', 'AMIRA_REALTIME_VOICE') || 'tiffany',
    aminaRealtimeSocketUrl: airsEnv('AIRS_REALTIME_SOCKET_URL', 'AMIRA_REALTIME_SOCKET_URL') || '',
    airsStudyAccessEnabled: airsEnv('AIRS_STUDY_ACCESS_ENABLED', 'AMIRA_STUDY_ACCESS_ENABLED') !== 'false',
    cognitoUserPoolId: process.env.FLOWST_COGNITO_USER_POOL_ID || '',
    cognitoClientId: process.env.FLOWST_COGNITO_CLIENT_ID || '',
    groqApiKey: process.env.GROQ_API_KEY || process.env.GROQ_API_TOKEN || '',
    groqModel: process.env.GROQ_MODEL || 'openai/gpt-oss-20b',
    flowstTextProvider: process.env.FLOWST_TEXT_PROVIDER || (process.env.QWEN_API_KEY || process.env.DASHSCOPE_API_KEY ? 'qwen' : 'groq'),
    qwenApiKey: process.env.QWEN_API_KEY || process.env.DASHSCOPE_API_KEY || '',
    qwenBaseUrl: process.env.QWEN_BASE_URL || 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    qwenModel: process.env.QWEN_MODEL || 'qwen-plus',
    elevenLabsModelId: process.env.ELEVENLABS_MODEL_ID || 'eleven_flash_v2_5',
    agentCoreEndpoint: process.env.AGENTCORE_ENDPOINT || '',
    agentCoreRuntimeArn: process.env.AGENTCORE_RUNTIME_ARN || '',
    agentCoreBearerToken: process.env.AGENTCORE_BEARER_TOKEN || '',
    neoImageProvider: process.env.NEO_IMAGE_PROVIDER || 'stability',
    neoBedrockModelId: process.env.NEO_BEDROCK_MODEL_ID || 'stability.stable-image-core-v1:1',
    neoBedrockEditModelId: process.env.NEO_BEDROCK_EDIT_MODEL_ID || 'stability.stable-image-control-structure-v1:0',
    neoAwsRegion: process.env.NEO_AWS_REGION || process.env.AWS_REGION || 'us-west-2',
    neoGenerationEnabled: process.env.NEO_GENERATION_ENABLED === 'true',
    elevenLabsApiKey: process.env.ELEVENLABS_API_KEY || '',
    elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_ID || '',
    studyAwsPollyVoiceId: process.env.FLOWST_STUDY_AWS_POLLY_VOICE_ID || 'Joanna',
    studyAwsVoiceTrialMaxSeconds: Number(process.env.FLOWST_STUDY_AWS_VOICE_TRIAL_MAX_SECONDS || 300),
    studyAwsVoiceTrialMaxCharacters: Number(process.env.FLOWST_STUDY_AWS_VOICE_TRIAL_MAX_CHARACTERS || 6000),
    studyAwsTranscribeUsdPerMinute: Number(process.env.FLOWST_STUDY_AWS_TRANSCRIBE_ESTIMATE_USD_PER_MINUTE || 0.03),
    studyAwsPollyUsdPerMillion: Number(process.env.FLOWST_STUDY_AWS_POLLY_ESTIMATE_USD_PER_MILLION || 16),
    studyBedrockModelId: process.env.FLOWST_STUDY_BEDROCK_MODEL_ID || 'us.amazon.nova-2-lite-v1:0',
    dynamoTable: process.env.FLOWST_DYNAMO_TABLE || '',
    curriculumBucket: process.env.FLOWST_CURRICULUM_BUCKET || '',
    communityMediaBucket: process.env.FLOWST_COMMUNITY_MEDIA_BUCKET || '',
    communityGuardrailId: process.env.FLOWST_COMMUNITY_GUARDRAIL_ID || '',
    communityGuardrailVersion: process.env.FLOWST_COMMUNITY_GUARDRAIL_VERSION || '',
    communitySafetyMode: process.env.FLOWST_COMMUNITY_SAFETY_MODE || 'aws',
    communityImageModerationConfidence: Number(process.env.FLOWST_COMMUNITY_IMAGE_MODERATION_CONFIDENCE || 75),
    awsRegion: process.env.AWS_REGION || 'us-east-1',
    public: {
      flowstHomeUrl: process.env.NUXT_PUBLIC_FLOWST_HOME_URL || (process.env.NODE_ENV !== 'production' ? 'http://localhost:3000/airs' : ''),
      studySourceFixtureMode: airsEnv('AIRS_SOURCE_FIXTURE_MODE', 'AMINA_SOURCE_FIXTURE_MODE') === 'true' && process.env.FLOWST_AUTH_MODE === 'mock' && process.env.NODE_ENV !== 'production',
      appSurface: 'airs',
      authRequired: process.env.NUXT_PUBLIC_AUTH_REQUIRED !== 'false',
      apiBaseUrl: '/api',
      schoolId: process.env.NUXT_PUBLIC_SCHOOL_ID || 'school-aster',
      demoMode: process.env.NUXT_PUBLIC_DEMO_MODE !== 'false',
      neoGenerationAvailable: process.env.NEO_GENERATION_ENABLED === 'true',
      studyAwsVoiceTrialMaxSeconds: Number(process.env.FLOWST_STUDY_AWS_VOICE_TRIAL_MAX_SECONDS || 300),
      studyAwsVoiceTrialMaxCharacters: Number(process.env.FLOWST_STUDY_AWS_VOICE_TRIAL_MAX_CHARACTERS || 6000),
    },
  },
  pwa: {
    registerType: 'autoUpdate',
    manifest: {
      name: 'Flowst Airs',
      short_name: 'Airs',
      description: 'Source-grounded learning and spoken practice.',
      theme_color: '#fffaf3',
      background_color: '#fffaf3',
      display: 'standalone',
      start_url: '/',
      icons: [
        { src: '/airs-icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' },
      ],
    },
    workbox: {
      navigateFallback: '/',
      // Keep the install lightweight. Large agent artwork loads normally on demand.
      globPatterns: ['**/*.{js,css,html,svg,woff2}'],
    },
  },
  nitro: {
    experimental: { websocket: true },
    vercel: { functions: { maxDuration: 120 } },
    preset: process.env.NITRO_PRESET || undefined,
  },
  typescript: {
    strict: true,
    typeCheck: false,
  },
})
