import {pacingAt,type StudyPacingState} from '../shared/studyPacing'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {createStudyConversation,getStudyConversation,getStudyChunks,saveStudyPlan} from '../server/services/studyRepository'
import {generateMisuPlan,validateMisuObjectives,buildMisuPlanningRequest} from '../server/services/studyMisu'
import {validateStudyPreferences} from '../server/services/studyPreferences'
import {changeStudyPacing,getStudyPacing,assertStudyPacingOpen} from '../server/services/studyPacing'
import {validSpeechAlignment,spokenCaption} from '../shared/studySpeech'
import {elevenSynthesizeTimedStudySpeech} from '../server/services/studyElevenSpeech'
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals()})
const preferences={purpose:'INTERVIEW' as const,scope:'BROAD' as const,timeBudgetMinutes:5,context:'',pacing:{mode:'TOPIC_BLOCKS' as const,practiceMinutes:5,breakMinutes:3 as const}}
async function approved(owner:string){vi.stubGlobal('useRuntimeConfig',()=>({flowstAuthMode:'mock',studySourceFixtureMode:true,public:{appSurface:'flowst'}}));const chat=await createStudyConversation(owner,'source.pdf','application/pdf',Buffer.from('fixture'),{kind:'PDF',sections:[{id:'one',label:'Page 1',text:'Retrieval practice means recall before checking notes.'}],excerpt:'Retrieval',provenance:{url:'https://example.com/fixture',fixture:true,provider:'Local fixture',hash:'x',retrievedAt:new Date().toISOString(),omissions:[]}},undefined,preferences);const draft=await generateMisuPlan(owner,chat.id);return saveStudyPlan(owner,chat.id,{...draft.plan,status:'APPROVED',approvedBy:owner,approvedAt:new Date().toISOString(),activeObjectiveId:draft.plan.objectives[0]!.id},draft.revision)}
describe('per-topic practice pacing',()=>{
 it('anchors a refreshed practice snapshot without counting elapsed time twice',()=>{const initial:StudyPacingState={revision:'r',blockId:'b',objectiveId:'o',phase:'PRACTICE',remainingMs:300000,startedAt:0,serverNow:0};const refreshed=pacingAt(initial,60000);expect(refreshed.remainingMs).toBe(240000);expect(pacingAt(refreshed,70000).remainingMs).toBe(230000)})
 it('plans three five-minute topics independently of the old five-minute total field',async()=>{const chat=await approved('pacing-plan');expect(chat.plan.objectives.map(o=>o.estimatedMinutes)).toEqual([5,5,5]);expect(chat.plan.estimatedTotalMinutes).toBe(15);expect(chat.plan.estimatedBreakMinutes).toBe(9);expect(buildMisuPlanningRequest(preferences,'source').system).toContain('not a total conversation budget')})
 it('bounds new pacing and leaves legacy preferences untouched',()=>{expect(validateStudyPreferences({...preferences,pacing:undefined}).pacing).toBeUndefined();for(const n of [4,16,5.5])expect(()=>validateStudyPreferences({...preferences,pacing:{...preferences.pacing,practiceMinutes:n}})).toThrow();expect(()=>validateStudyPreferences({...preferences,pacing:{...preferences.pacing,breakMinutes:4}})).toThrow()})
 it('persists clocks, pauses, blocks early resume, and resets after a break without completing a topic',async()=>{vi.useFakeTimers();vi.setSystemTime(1000000);const chat=await approved('pacing-clock');let state=await changeStudyPacing(chat.ownerId,chat.id,'START','');expect(state?.remainingMs).toBe(300000);vi.advanceTimersByTime(60000);state=await changeStudyPacing(chat.ownerId,chat.id,'PAUSE',state!.revision);expect(state?.remainingMs).toBe(240000);vi.advanceTimersByTime(60000);expect((await getStudyPacing(chat.ownerId,chat.id))?.remainingMs).toBe(240000);state=await changeStudyPacing(chat.ownerId,chat.id,'RESUME',state!.revision);vi.advanceTimersByTime(240000);expect((await getStudyPacing(chat.ownerId,chat.id))?.phase).toBe('BREAK_DUE');state=await changeStudyPacing(chat.ownerId,chat.id,'BREAK',state!.revision);await expect(assertStudyPacingOpen(chat)).rejects.toMatchObject({statusCode:409});await expect(changeStudyPacing(chat.ownerId,chat.id,'RESUME',state!.revision)).rejects.toMatchObject({statusCode:409});vi.advanceTimersByTime(180000);state=await changeStudyPacing(chat.ownerId,chat.id,'RESUME',state!.revision);expect(state?.remainingMs).toBe(300000);expect((await getStudyConversation(chat.ownerId,chat.id)).plan.courseCompletedAt).toBeUndefined();await expect(changeStudyPacing('other',chat.id,'START','')).rejects.toMatchObject({statusCode:404})})
 it('allows only the take reserved before expiry to finish, and rejects stale timer writes',async()=>{vi.useFakeTimers();vi.setSystemTime(1000000);const chat=await approved('pacing-take');let state=await changeStudyPacing(chat.ownerId,chat.id,'START','');const old=state!.revision;state=await changeStudyPacing(chat.ownerId,chat.id,'RECORD',old,undefined,'take-one');await expect(changeStudyPacing(chat.ownerId,chat.id,'PAUSE',old)).rejects.toMatchObject({statusCode:409});vi.advanceTimersByTime(300000);await expect(assertStudyPacingOpen(chat)).rejects.toMatchObject({statusCode:409});await expect(assertStudyPacingOpen(chat,undefined,'take-one')).resolves.toMatchObject({phase:'BREAK_DUE'});await expect(assertStudyPacingOpen(chat,undefined,'another-take')).rejects.toMatchObject({statusCode:409})})
})
describe('spoken captions and synthesis',()=>{
 const alignment={characters:['H','i'],character_start_times_seconds:[0,0.5],character_end_times_seconds:[0.4,1]}
 it('uses measured playback position and refuses invalid provider alignment',()=>{expect(spokenCaption(alignment,'Hi',0.1)).toBe('H');expect(spokenCaption(alignment,'Hi',0.6)).toBe('Hi');expect(validSpeechAlignment({...alignment,character_start_times_seconds:[1,0]})).toBeNull();expect(spokenCaption(null,'Saved text',0.1)).toBe('Saved text')})
 it('reserves one synthesis and returns timing with the same audio, without retrying paid errors',async()=>{const chat=await approved('pacing-speech');vi.stubGlobal('useRuntimeConfig',()=>({flowstAuthMode:'mock',elevenLabsApiKey:'test',elevenLabsVoiceId:'voice',studyAwsVoiceTrialMaxCharacters:6000}));const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({audio_base64:Buffer.from('mock-audio').toString('base64'),alignment})));vi.stubGlobal('fetch',fetcher);const packet=await elevenSynthesizeTimedStudySpeech(chat.ownerId,chat,'Hi');expect(packet.alignment).toEqual(alignment);expect(fetcher.mock.calls[0]![0]).toContain('/with-timestamps');expect(fetcher).toHaveBeenCalledTimes(1);fetcher.mockResolvedValue(new Response('',{status:503}));await expect(elevenSynthesizeTimedStudySpeech(chat.ownerId,chat,'Retry')).rejects.toMatchObject({statusCode:503});expect(fetcher).toHaveBeenCalledTimes(2)})
})
