<script setup lang="ts">
import type { LearnerContext } from '~/shared/airsOrchestration'
const auth=useAuth()
const context=ref<LearnerContext>({background:'',goals:'',audience:''})
const loading=ref(true),saved=ref(false),busy=ref(false),error=ref(''),memory=ref<any>(null)
onMounted(async()=>{try{const result=await auth.authorizedFetch<any>('/api/study/context');context.value={background:result.context.background,goals:result.context.goals,audience:result.context.audience};memory.value=result.memory;await nextTick();saved.value=Boolean(result.context.recordedAt)}catch{error.value='Your context could not be loaded. You can retry saving it.'}finally{loading.value=false}})
watch(context,()=>{if(!loading.value)saved.value=false},{deep:true})
async function save(){busy.value=true;error.value='';try{await auth.authorizedFetch('/api/study/context',{method:'PUT',body:context.value});saved.value=true}catch{error.value='We could not save your context. Try again.'}finally{busy.value=false}}
</script>
<template><section class="context-card" aria-label="Your learning context"><h2>Your context for Misu</h2><p>Use what you want Misu to know. These are your statements, not inferred abilities.</p><fieldset :disabled="loading || busy"><label>Background<input v-model="context.background" maxlength="400" placeholder="Early-career developer and content creator" /></label><label>Career or communication goals<input v-model="context.goals" maxlength="400" placeholder="Explain my project clearly in interviews" /></label><label>Who you want to speak to<input v-model="context.audience" maxlength="200" placeholder="A technical interviewer" /></label></fieldset><button type="button" :disabled="busy || loading" @click="save">{{ busy ? 'Saving…' : 'Save context' }}</button><p role="status">{{ loading ? 'Loading your context…' : error || (saved ? 'Context saved. Misu will use this when preparing your next plan.' : 'Edit or save your context before creating a plan.') }}</p><p v-if="memory">A previous evidence review is available to Misu. It is an observation from that session, not a judgment of your ability.</p></section></template>
<style scoped>.context-card fieldset{border:0;padding:0;margin:0}.context-card{padding:20px;margin:16px 0;border:1px solid #dbdee5;border-radius:16px;background:#fff}h2{font-size:1.1rem}p{font-size:.85rem;line-height:1.6}label{display:block;font-size:.85rem;margin:12px 0}input{display:block;width:100%;box-sizing:border-box;padding:12px;margin-top:6px;border:1px solid #bfc6d2;border-radius:8px}button{padding:12px 16px;border:1px solid #bfc6d2;border-radius:8px}</style>
