import {expect,test} from '@playwright/test'

test('Misu guides setup and prepares Amina without starting a microphone or voice lease',async({page})=>{
 let voiceStarts=0,welcomeReads=0
 await page.addInitScript(()=>{(window as any).__micRequests=0;Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{(window as any).__micRequests++;throw new DOMException('Test permission denial','NotAllowedError')}})})
 page.on('request',request=>{if(request.method()==='POST' && /\/live\/start/.test(request.url()))voiceStarts++})
 await page.route('**/api/study/conversations/*/live',route=>route.fulfill({json:{enabled:true,socketUrl:'',provider:'elevenlabs',message:''}}))
 await page.route('**/api/study/conversations/*/speech',route=>route.fulfill({status:503,json:{statusMessage:'Fixture welcome playback unavailable'}}))
 await page.route('**/api/study/conversations/*/welcome',async route=>{welcomeReads++;const response=await route.fetch();await new Promise(done=>setTimeout(done,500));await route.fulfill({response})})
 await page.goto('/airs/new',{waitUntil:'domcontentloaded'})
 await expect(page.getByRole('region',{name:'Your learning context'})).toBeVisible({timeout:90000})
 expect(await page.locator('iframe').count()).toBe(0)
 await expect(page.getByLabel('Public source link')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Save context',exact:true}).or(page.getByRole('button',{name:'Continue',exact:true}))).toBeVisible()
 if(await page.getByRole('button',{name:'Edit my context',exact:true}).isVisible())await page.getByRole('button',{name:'Edit my context',exact:true}).click()
 await page.getByLabel('Share context about yourself',{exact:true}).fill('Early-career developer and content creator. I want to explain my projects in interviews.')
 await page.getByRole('button',{name:'Save context',exact:true}).click()
 await expect(page.getByLabel('My understanding — you can edit it')).toBeVisible()
 await page.getByLabel('My understanding — you can edit it').fill('I want to explain my projects clearly in interviews.')
 await page.getByRole('button',{name:'Continue',exact:true}).click()
 await page.getByLabel('Link or transcript',{exact:true}).check()
 await page.getByRole('button',{name:'Try video fixture'}).click()
 await expect(page.getByText('Demonstration speech transcript',{exact:true})).toBeVisible()
 await expect(page.getByLabel('Practice time per topic',{exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'Use this source',exact:true}).click()
 await page.getByLabel('What is this session for?').selectOption('INTERVIEW')
 await page.getByRole('button',{name:'Draft my plan',exact:true}).click()
 await expect(page.getByRole('region',{name:'Misu learning planner'})).toBeVisible({timeout:90000})
 await expect(page).toHaveURL(/\/airs\/[a-f0-9-]+$/)
 await page.getByText('What this plan is based on',{exact:true}).click()
 await expect(page.getByText('I want to explain my projects clearly in interviews.',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Adjust plan',exact:true}).click()
 await page.getByLabel('What would you like me to change?').fill('Focus on explaining the source in an interview.')
 await page.getByRole('button',{name:'Draft adjusted plan',exact:true}).click()
 await expect(page.getByRole('button',{name:'Approve plan',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'Approve plan',exact:true}).click()
 await expect(page.getByRole('region',{name:'Preparing your conversation'})).toBeVisible()
 await expect(page.getByText('Your welcome is ready. Microphone off.',{exact:true})).toBeVisible({timeout:30000})
 await expect(page.getByRole('button',{name:'Start conversation',exact:true})).toBeVisible()
 await expect(page.getByText('Spoken playback is unavailable.',{exact:false})).toBeVisible()
 expect(voiceStarts).toBe(0);expect(await page.evaluate(()=>(window as any).__micRequests)).toBe(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'test-results/airs-prepared-'+test.info().project.name+'.png',fullPage:true})
 const currentWelcomeReads=welcomeReads
 await page.reload({waitUntil:'domcontentloaded'})
 await expect(page.getByRole('button',{name:'Start conversation',exact:true})).toBeVisible()
 expect(welcomeReads).toBe(currentWelcomeReads);expect(voiceStarts).toBe(0)
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(page.getByRole('region',{name:'Preparing your conversation'})).toBeVisible()
 let introduced=false
 const introId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
 const intro={id:introId,role:'AMIRA',kind:'INTRO',text:'Fixture introduction. What does retrieval practice mean?',createdAt:new Date().toISOString(),mode:'DISCUSSION',sources:[]}
 await page.route('**/api/study/conversations/*/control',async route=>{introduced=true;await route.fulfill({json:{agentTurn:intro}})})
 await page.route(/\/api\/study\/conversations\/[a-f0-9-]+$/,async route=>{const response=await route.fetch();const data=await response.json();if(introduced && !data.turns.some((t:any)=>t.id===introId))data.turns.push(intro);await route.fulfill({json:data})})
 const wav=Buffer.alloc(44+16000*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40)
 await page.unroute('**/api/study/conversations/*/speech')
 let releaseAudio!:()=>void
 const audioGate=new Promise<void>(resolve=>{releaseAudio=resolve})
 await page.route('**/api/study/conversations/*/speech',async route=>{await audioGate;await route.fulfill({json:{audioBase64:wav.toString('base64'),mimeType:'audio/wav',spokenText:intro.text,alignment:null}})})
 const starting=page.getByRole('button',{name:'Start conversation',exact:true}).click()
 await expect(page.getByText('Preparing Amina’s voice',{exact:true})).toBeVisible()
 await expect(page.getByText(intro.text,{exact:true})).not.toBeVisible()
 expect(await page.evaluate(()=>(window as any).__micRequests)).toBe(0)
 await expect(page.getByRole('region',{name:'Practice and break timer'})).toContainText('Current topic practice')
 releaseAudio();await starting
 await expect(page.getByText('Amina is waiting for your turn',{exact:true})).toBeVisible({timeout:15000})
 await page.getByRole('button',{name:'Pause practice',exact:true}).click()
 await expect(page.getByRole('region',{name:'Practice and break timer'})).toContainText('Practice paused')
 await page.getByRole('button',{name:'Resume practice',exact:true}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'test-results/airs-voice-turn-'+test.info().project.name+'.png',fullPage:true})
 await page.getByRole('button',{name:'Start recording',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>(window as any).__micRequests)).toBe(1)
 expect(voiceStarts).toBe(0)
})
